"""Tests for the click command surface in ``sdf.cli``."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from . import __version__
from .cli import main

ROOT = Path(__file__).resolve().parents[2]
SAMPLE_CSV = str(ROOT / "data" / "sample_online_retail_ii.csv")
COMMANDS = [
    "demo",
    "export",
    "backtest",
    "synth",
    "tstr",
    "sdv",
    "agent",
    "pipeline",
    "impact",
    "scenarios",
    "privacy",
    "validate",
    "hooks",
]


def run(*args: str):
    return CliRunner().invoke(main, list(args))


def test_no_command_runs_demo():
    result = run()
    assert result.exit_code == 0, result.output
    assert "AI Warehouse Management (framework demo)" in result.output


def test_help_lists_every_command():
    result = run("--help")
    assert result.exit_code == 0
    for name in COMMANDS:
        assert name in result.output


def test_version():
    result = run("--version")
    assert result.exit_code == 0
    assert __version__ in result.output


@pytest.mark.parametrize(
    ("args", "marker"),
    [
        (("demo",), "[Application] KPIs:"),
        (("pipeline",), "DAG run record"),
        (("impact",), "ANNUALISED net saving"),
        (("scenarios",), "promo_spike"),
        (("agent", "should I reorder and what is the money impact?"), "proposed actions (need approval)"),
        (("agent",), "Q: what can you do?"),
        (("backtest", SAMPLE_CSV), "best (lowest MAE)"),
        (("synth", SAMPLE_CSV), "fidelity score"),
        (("tstr", SAMPLE_CSV), "ratio TSTR/TRTR"),
        (("privacy", SAMPLE_CSV), "clone_risk_pct"),
    ],
)
def test_commands_run(args, marker):
    result = run(*args)
    assert result.exit_code == 0, result.output
    assert marker in result.output


def test_csv_argument_defaults_to_bundled_sample(monkeypatch):
    monkeypatch.chdir(ROOT)
    result = run("backtest")
    assert result.exit_code == 0, result.output
    assert "sample_online_retail_ii.csv" in result.output


def test_export_writes_six_csvs(tmp_path):
    outdir = tmp_path / "out"
    result = run("export", str(outdir))
    assert result.exit_code == 0, result.output
    names = sorted(p.name for p in outdir.iterdir())
    assert names == ["inbound.csv", "inventory.csv", "locations.csv", "outbound.csv", "sensors.csv", "skus.csv"]


def test_missing_csv_is_a_usage_error(tmp_path):
    result = run("backtest", str(tmp_path / "missing.csv"))
    assert result.exit_code == 2
    assert "does not exist" in result.output


def test_unknown_command_is_a_usage_error():
    result = run("frobnicate")
    assert result.exit_code == 2
    assert "No such command" in result.output


def test_sdv_without_optional_extra_exits_1():
    if importlib.util.find_spec("copulas") and importlib.util.find_spec("sdmetrics"):
        pytest.skip("synthesis extra installed; the ImportError path is not reachable")
    result = run("sdv", SAMPLE_CSV)
    assert result.exit_code == 1
    assert "uv sync --extra synthesis" in result.output


def test_validate_prints_the_snapshot_as_json():
    result = run("validate")
    assert result.exit_code == 0, result.output
    snap = json.loads(result.output)
    assert set(snap) == {"default_world", "sample_csv", "retail_csv"}
    assert snap["default_world"]["abc"] == {"A": 39, "B": 55, "C": 106}


def test_validate_update_doc_rewrites_only_the_block(tmp_path):
    doc = tmp_path / "doc.md"
    doc.write_text("# Doc\n<!-- sdf-validate:begin -->\nstale\n<!-- sdf-validate:end -->\ntail\n")
    result = run("validate", "--update-doc", str(doc))
    assert result.exit_code == 0, result.output
    text = doc.read_text()
    assert "stale" not in text and "### Default world" in text
    assert text.startswith("# Doc\n") and text.endswith("<!-- sdf-validate:end -->\ntail\n")
    assert "already up to date" in run("validate", "--update-doc", str(doc)).output


def test_validate_prints_markdown():
    result = run("validate", "--format", "markdown")
    assert result.exit_code == 0, result.output
    assert result.output.startswith("_Generated by `uv run sdf validate")
    for heading in (
        "### Default world",
        "### `sample_online_retail_ii.csv` (daily;",
        "### `online_retail_ii_2010_10k.csv` (hourly;",
    ):
        assert heading in result.output
    assert "| model | MAE | RMSE | MAPE % | WAPE % | bias |" in result.output


def test_date_format_option_is_passed_to_the_loader():
    ok = run("backtest", SAMPLE_CSV, "--date-format", "%Y-%m-%d %H:%M:%S")
    assert ok.exit_code == 0, ok.output
    assert "best (lowest MAE)" in ok.output


@pytest.mark.parametrize("command", ["backtest", "synth", "tstr", "privacy"])
def test_csv_commands_exit_1_when_no_row_is_usable(command):
    result = run(command, SAMPLE_CSV, "--date-format", "%d/%m/%Y %H:%M")
    assert result.exit_code == 1, result.output
    assert "no usable rows" in result.output


@pytest.mark.parametrize(
    ("command", "valid", "invalid"),
    [("synth", "seasonal-profile", "bootstrap-table"), ("tstr", "seasonal-profile", "warehouse-spec")],
)
def test_synthesizer_option_accepts_only_matching_names(command, valid, invalid):
    ok = run(command, SAMPLE_CSV, "--synthesizer", valid)
    assert ok.exit_code == 0, ok.output
    assert "synthesizer" in ok.output and valid in ok.output
    wrong = run(command, SAMPLE_CSV, "--synthesizer", invalid)
    assert wrong.exit_code == 2 and "seasonal-profile" in wrong.output


def test_unknown_synthesizer_is_a_usage_error_listing_the_names():
    result = run("privacy", SAMPLE_CSV, "--synthesizer", "nope")
    assert result.exit_code == 2
    assert "Invalid value for '--synthesizer': 'nope'" in result.output and "bootstrap-table" in result.output


def test_hooks_prints_the_index_and_updates_a_doc(tmp_path, monkeypatch):
    monkeypatch.chdir(ROOT)
    result = run("hooks")
    assert result.exit_code == 0, result.output
    assert "| C2 | Replenishment |" in result.output
    doc = tmp_path / "notes.md"  # holds no row table: the rows come from --checklist
    doc.write_text("Intro\n\n<!-- sdf-hooks:begin -->\nstale\n<!-- sdf-hooks:end -->\n", encoding="utf-8")
    assert "updated" in run("hooks", "--update-doc", str(doc)).output
    text = doc.read_text(encoding="utf-8")
    assert "| C2 | Replenishment |" in text and "stale" not in text
    assert f"--update-doc {doc}`" in text  # the header names the document it regenerates
    assert "already up to date" in run("hooks", "--update-doc", str(doc)).output


def test_hooks_fails_on_an_unknown_row(tmp_path):
    doc = tmp_path / "checklist.md"
    doc.write_text("| # | Item |\n|---|---|\n| C1 | Demand forecast |\n", encoding="utf-8")
    result = run("hooks", "--checklist", str(doc))
    assert result.exit_code == 1 and "names no checklist row" in result.output
