"""Tests for the click command surface in ``sdf.cli``."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from . import __version__
from .cli import main

ROOT = Path(__file__).resolve().parents[2]
SAMPLE_CSV = str(ROOT / "data" / "sample_online_retail_ii.csv")
COMMANDS = [
    "demo",
    "export",
    "backtest",
    "synth",
    "tstr",
    "sdv",
    "agent",
    "pipeline",
    "impact",
    "scenarios",
    "effects",
    "estimate",
    "forecast",
    "anomalies",
    "privacy",
    "validate",
    "hooks",
]


def run(*args: str):
    return CliRunner().invoke(main, list(args))


def test_no_command_runs_demo():
    result = run()
    assert result.exit_code == 0, result.output
    assert "AI Warehouse Management (framework demo)" in result.output


def test_help_lists_every_command():
    result = run("--help")
    assert result.exit_code == 0
    for name in COMMANDS:
        assert name in result.output


def test_version():
    result = run("--version")
    assert result.exit_code == 0
    assert __version__ in result.output


@pytest.mark.parametrize(
    ("args", "marker"),
    [
        (("demo",), "[Application] KPIs:"),
        (("pipeline",), "DAG run record"),
        (("impact",), "ANNUALISED net saving"),
        (("scenarios",), "promo_spike"),
        (("agent", "should I reorder and what is the money impact?"), "proposed actions (need approval)"),
        (("agent",), "Q: what can you do?"),
        (("backtest", SAMPLE_CSV), "best (lowest MAE)"),
        (("synth", SAMPLE_CSV), "fidelity score"),
        (("tstr", SAMPLE_CSV), "ratio TSTR/TRTR"),
        (("privacy", SAMPLE_CSV), "clone_risk_pct"),
        (("privacy", SAMPLE_CSV), "telling columns : price"),
        (("privacy", SAMPLE_CSV, "--synthesizer", "bayesian-network"), "synthesizer     : bayesian-network"),
    ],
)
def test_commands_run(args, marker):
    result = run(*args)
    assert result.exit_code == 0, result.output
    assert marker in result.output


def test_csv_argument_defaults_to_bundled_sample(monkeypatch):
    monkeypatch.chdir(ROOT)
    result = run("backtest")
    assert result.exit_code == 0, result.output
    assert "sample_online_retail_ii.csv" in result.output


def test_export_writes_six_csvs(tmp_path):
    outdir = tmp_path / "out"
    result = run("export", str(outdir))
    assert result.exit_code == 0, result.output
    names = sorted(p.name for p in outdir.iterdir())
    assert names == ["inbound.csv", "inventory.csv", "locations.csv", "outbound.csv", "sensors.csv", "skus.csv"]


def test_missing_csv_is_a_usage_error(tmp_path):
    result = run("backtest", str(tmp_path / "missing.csv"))
    assert result.exit_code == 2
    assert "does not exist" in result.output


def test_unknown_command_is_a_usage_error():
    result = run("frobnicate")
    assert result.exit_code == 2
    assert "No such command" in result.output


def test_sdv_without_optional_extra_exits_1():
    if importlib.util.find_spec("copulas") and importlib.util.find_spec("sdmetrics"):
        pytest.skip("synthesis extra installed; the ImportError path is not reachable")
    result = run("sdv", SAMPLE_CSV)
    assert result.exit_code == 1
    assert "uv sync --extra synthesis" in result.output


def test_validate_prints_the_snapshot_as_json():
    result = run("validate")
    assert result.exit_code == 0, result.output
    snap = json.loads(result.output)
    assert set(snap) == {"default_world", "sample_csv", "retail_csv"}
    assert snap["default_world"]["abc"] == {"A": 39, "B": 55, "C": 106}


def test_validate_update_doc_rewrites_only_the_block(tmp_path):
    doc = tmp_path / "doc.md"
    doc.write_text("# Doc\n<!-- sdf-validate:begin -->\nstale\n<!-- sdf-validate:end -->\ntail\n")
    result = run("validate", "--update-doc", str(doc))
    assert result.exit_code == 0, result.output
    text = doc.read_text()
    assert "stale" not in text and "### Default world" in text
    assert text.startswith("# Doc\n") and text.endswith("<!-- sdf-validate:end -->\ntail\n")
    assert "already up to date" in run("validate", "--update-doc", str(doc)).output


def test_validate_prints_markdown():
    result = run("validate", "--format", "markdown")
    assert result.exit_code == 0, result.output
    assert result.output.startswith("_Generated by `uv run sdf validate")
    for heading in (
        "### Default world",
        "### `sample_online_retail_ii.csv` (daily;",
        "### `online_retail_ii_2010_10k.csv` (hourly;",
    ):
        assert heading in result.output
    assert "| model | MAE | RMSE | MAPE % | WAPE % | bias |" in result.output


def test_date_format_option_is_passed_to_the_loader():
    ok = run("backtest", SAMPLE_CSV, "--date-format", "%Y-%m-%d %H:%M:%S")
    assert ok.exit_code == 0, ok.output
    assert "best (lowest MAE)" in ok.output


@pytest.mark.parametrize("command", ["backtest", "synth", "tstr", "privacy"])
def test_csv_commands_exit_1_when_no_row_is_usable(command):
    result = run(command, SAMPLE_CSV, "--date-format", "%d/%m/%Y %H:%M")
    assert result.exit_code == 1, result.output
    assert "no usable rows" in result.output


@pytest.mark.parametrize(
    ("command", "valid", "invalid"),
    [("synth", "seasonal-profile", "bootstrap-table"), ("tstr", "seasonal-profile", "warehouse-spec")],
)
def test_synthesizer_option_accepts_only_matching_names(command, valid, invalid):
    ok = run(command, SAMPLE_CSV, "--synthesizer", valid)
    assert ok.exit_code == 0, ok.output
    assert "synthesizer" in ok.output and valid in ok.output
    wrong = run(command, SAMPLE_CSV, "--synthesizer", invalid)
    assert wrong.exit_code == 2 and "seasonal-profile" in wrong.output


def test_unknown_synthesizer_is_a_usage_error_listing_the_names():
    result = run("privacy", SAMPLE_CSV, "--synthesizer", "nope")
    assert result.exit_code == 2
    assert "Invalid value for '--synthesizer': 'nope'" in result.output and "bootstrap-table" in result.output


def test_hooks_prints_the_index_and_updates_a_doc(tmp_path, monkeypatch):
    monkeypatch.chdir(ROOT)
    result = run("hooks")
    assert result.exit_code == 0, result.output
    assert "| C2 | Replenishment |" in result.output
    doc = tmp_path / "notes.md"  # holds no row table: the rows come from --checklist
    doc.write_text("Intro\n\n<!-- sdf-hooks:begin -->\nstale\n<!-- sdf-hooks:end -->\n", encoding="utf-8")
    assert "updated" in run("hooks", "--update-doc", str(doc)).output
    text = doc.read_text(encoding="utf-8")
    assert "| C2 | Replenishment |" in text and "stale" not in text
    assert f"--update-doc {doc}`" in text  # the header names the document it regenerates
    assert "already up to date" in run("hooks", "--update-doc", str(doc)).output


def test_hooks_update_doc_needs_the_generated_block(tmp_path, monkeypatch):
    monkeypatch.chdir(ROOT)
    doc = tmp_path / "plain.md"
    doc.write_text("no generated block here\n", encoding="utf-8")
    result = run("hooks", "--update-doc", str(doc))
    assert result.exit_code == 1 and "sdf-hooks:begin" in result.output
    assert doc.read_text(encoding="utf-8") == "no generated block here\n"


def test_hooks_fails_on_an_unknown_row(tmp_path):
    doc = tmp_path / "checklist.md"
    doc.write_text("| # | Item |\n|---|---|\n| C1 | Demand forecast |\n", encoding="utf-8")
    result = run("hooks", "--checklist", str(doc))
    assert result.exit_code == 1 and "names no checklist row" in result.output


@pytest.mark.parametrize(
    ("args", "kind"),
    [(("agent", "should I reorder?"), "tool"), (("pipeline",), "step")],
)
def test_audit_log_option_writes_the_full_run(tmp_path, args, kind):
    sink = tmp_path / "audit.jsonl"
    result = run(*args, "--audit-log", str(sink))
    assert result.exit_code == 0, result.output
    assert f"full audit log appended to {sink}" in result.output
    lines = [json.loads(line) for line in sink.read_text(encoding="utf-8").splitlines()]
    entries, summary = lines[:-1], lines[-1]
    assert entries and all(e["record"] == "entry" and e["kind"] == kind for e in entries)
    assert summary["record"] == "summary" and summary["steps"] == len(entries)


def test_effects_prints_each_effect_with_its_interval_and_writes_csv(tmp_path):
    out = tmp_path / "effects.csv"
    result = run("effects", "--intervention", "promo_spike", "--replicates", "2", "--csv", str(out))
    assert result.exit_code == 0, result.output
    lines = result.output.splitlines()
    assert lines[0] == "promo_spike vs baseline, service-level-95, 2 paired replicates, 95 % intervals"
    assert lines[1].split() == ["metric", "baseline", "treated", "effect", "interval"]
    assert any(line.startswith("holding_cost") and " … " in line for line in lines)
    header = out.read_text(encoding="utf-8").splitlines()[0]
    assert header.startswith("intervention,policy,metric,baseline,treated,effect,ci_low,ci_high")


def test_effects_groups_by_intervention_and_policy_and_marks_intervals_covering_zero():
    args = ["--intervention", "promo_spike", "--intervention", "supply_disruption"]
    result = run("effects", *args, "--policy", "naive", "--outcome", "active_stockouts", "--replicates", "2")
    assert result.exit_code == 0, result.output
    assert "promo_spike · naive" in result.output and "supply_disruption · naive" in result.output
    assert "(covers 0)" in result.output


@pytest.mark.parametrize(
    ("args", "message"),
    [
        (["--intervention", "baseline"], "baseline is what every intervention is compared with"),
        (["--intervention", "nope"], "unknown intervention 'nope'"),
        (["--intervention", "promo_spike", "--replicates", "1"], "replicates must be from 2 to 20"),
        (["--intervention", "promo_spike", "--policy", "naive:0.9"], "only service-level takes a level"),
        (["--intervention", "promo_spike", "--policy", "service-level:high"], "the level must be a number"),
        (["--intervention", "promo_spike", "--policy", "service-level:1.2"], "above 0.5 and below 1"),
        (["--intervention", "promo_spike", "--policy", "service-level:0.5"], "above 0.5 and below 1"),
    ],
)
def test_effects_refuses_an_invalid_study(args, message):
    result = run("effects", *args)
    assert result.exit_code != 0 and message in result.output


def test_estimate_scores_the_built_ins_against_the_benchmark_s_truth(tmp_path):
    out = tmp_path / "scores.csv"
    result = run("estimate", "--confounding", "1", "--csv", str(out))
    assert result.exit_code == 0, result.output
    lines = result.output.splitlines()
    assert lines[0].startswith("promotion benchmark: 200 SKUs, uplift 30 %, confounding 1, seed 7; true effect +")
    assert lines[0].endswith("units/week; adjusting for log_demand, abc_class, log_price")
    assert lines[1].split() == ["estimator", "effect", "95", "%", "interval", "bias", "covers"]
    rows = {line.split()[0]: line.split() for line in lines[2:5]}
    assert list(rows) == ["difference-in-means", "regression-adjustment", "ipw"]
    assert rows["difference-in-means"][-1] == "no" and rows["regression-adjustment"][-1] == "yes"
    header = out.read_text(encoding="utf-8").splitlines()[0]
    assert (
        header
        == "estimator,effect,ci_low,ci_high,true_effect,bias,relative_bias,covers,n_treated,n_control,seconds,method"
    )


def test_estimate_drops_covariates_and_refuses_what_it_cannot_run():
    result = run("estimate", "--drop", "log_demand", "--drop", "abc_class", "--estimator", "regression-adjustment")
    assert result.exit_code == 0 and "adjusting for log_price" in result.output
    assert result.output.splitlines()[2].split()[-1] == "no"  # without the demand proxies the bias returns
    for args, message in (
        (["--drop", "sku_id"], "--drop sku_id: the benchmark's covariates are"),
        (["--estimator", "nope"], "unknown estimator 'nope'"),
        (["--confounding", "4"], "confounding must be from 0.0 to 3.0, got 4.0"),
    ):
        refused = run("estimate", *args)
        assert refused.exit_code != 0 and message in refused.output, refused.output


def test_forecast_backtests_the_built_ins_on_the_benchmark_against_its_truth(tmp_path):
    out = tmp_path / "scores.csv"
    result = run("forecast", "--benchmark", "--horizon", "7", "--origins", "2", "--csv", str(out))
    assert result.exit_code == 0, result.output
    lines = result.output.splitlines()
    assert lines[0].startswith("demand benchmark (seed 7): 200 SKUs × 365 days; 2 origins from ")
    assert lines[1].split()[:3] == ["forecaster", "WAPE", "vs"]
    names = [line.split()[0] for line in lines[2:8]]
    assert names == ["mean", "naive", "moving-average", "seasonal-naive", "seasonal-linear", "true-distribution"]
    assert "no forecaster beats its pinball loss on average" in result.output
    header = out.read_text(encoding="utf-8").splitlines()[0]
    assert header.startswith("forecaster,wape,relative_wape,bias,mae,pinball,coverage_open,coverage_closed,nominal")


def test_forecast_takes_parameters_and_refuses_what_it_cannot_run():
    result = run("forecast", "-f", "moving-average", "--param", "moving-average.window=28", "--origins", "2")
    assert result.exit_code == 0 and result.output.startswith("default world: 200 SKUs × 90 days"), result.output
    for args, message in (
        (["-f", "nope"], "unknown forecaster 'nope'"),
        (["--param", "moving-average.window=0"], "moving-average: window must be from 1 to 365, got 0"),
        (["--param", "window=3"], "write FORECASTER.NAME=VALUE"),
        (["--seed", "3"], "--seed draws the benchmark; add --benchmark"),
        (["--horizon", "60"], "horizon must be a whole number from 1 to 56"),
    ):
        refused = run("forecast", *args)
        assert refused.exit_code != 0 and message in refused.output, refused.output


def test_anomalies_scores_the_built_ins_on_injected_anomalies(tmp_path):
    out = tmp_path / "scores.csv"
    result = run("anomalies", "--benchmark", "--csv", str(out))
    assert result.exit_code == 0, result.output
    lines = result.output.splitlines()
    assert lines[0] == "default world: 200 SKUs × 90 days; signals demand, on_hand, receipts"
    assert lines[1].startswith("injected 180 anomalies (rate 0.01, seed 7): ")
    shrinkage = next(
        line.split() for line in lines if line.startswith("isolation-forest") and " shrinkage  threshold" in line
    )
    assert float(shrinkage[4]) >= 0.8  # recall
    assert (
        out.read_text(encoding="utf-8").splitlines()[0] == "detector,kind,cut,precision,recall,f1,flagged,seconds,error"
    )


def test_anomalies_lists_detections_and_refuses_an_unknown_detector():
    result = run("anomalies", "-d", "seasonal-residual")
    assert result.exit_code == 0, result.output
    assert "seasonal-residual: " in result.output and "SKU-days flagged" in result.output
    bad = run("anomalies", "-d", "nope")
    assert bad.exit_code == 1 and "unknown detector 'nope'" in bad.output


def test_anomalies_reports_a_detector_s_own_failure_without_a_traceback(monkeypatch):
    from typing import ClassVar

    from .analytics.detectors import DetectorInfo, DetectorRegistry

    class Crashes:
        info: ClassVar[DetectorInfo] = DetectorInfo("crashes", "fails on every frame")

        def scores(self, frame):
            raise RuntimeError("out of memory")

        def detect(self, frame):
            return []

    reg = DetectorRegistry()
    reg.register(Crashes)
    monkeypatch.setattr("sdf.cli.default_detectors", lambda: reg)
    result = run("anomalies", "-d", "crashes")
    assert result.exit_code == 1 and "crashes failed: RuntimeError: out of memory" in result.output
    assert result.exception is None or isinstance(result.exception, SystemExit)


def test_privacy_reports_a_synthesizer_s_own_failure_without_a_traceback(monkeypatch, capsys):
    from typing import ClassVar

    from .cli import cmd_privacy
    from .synthesis.api import SynthesizerInfo
    from .synthesis.registry import default_registry

    class Wide:
        info: ClassVar[SynthesizerInfo] = SynthesizerInfo("wide", "table", True, "one value too many per row")

        def fit(self, data):
            self._rows = data.rows
            return self

        def sample(self, n=None, *, seed=None):
            return [(*r, 0.0) for r in self._rows]

    reg = default_registry()
    reg.register(Wide)
    monkeypatch.setattr("sdf.validation.evaluation.default_registry", lambda: reg)
    assert cmd_privacy(SAMPLE_CSV, synthesizer="wide") == 1
    assert "wide failed while sampling from it: a row of 5 values" in capsys.readouterr().err
