"""Hook markers: where a real algorithm or real data plugs into the framework.

A marker is ``ALGORITHM-HOOK[<ID>]: <text>`` or ``DATA-HOOK[<ID>]: <text>`` in a
comment, docstring or printed hint, where ``<ID>`` is a row of
``docs/ALGORITHM_AND_DATA_CHECKLIST.md`` (A1, C2, D4, …). Prose that names the
convention itself writes it in double backticks and is not a marker.

This module finds the markers, reads the checklist's IDs and renders the code
index that the checklist embeds between the ``sdf-hooks`` markers
(``uv run sdf hooks --update-doc docs/ALGORITHM_AND_DATA_CHECKLIST.md``).
Locations are ``path::symbol`` (the enclosing function or class), so ordinary
edits do not change the index.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent
DOC_BEGIN = "<!-- sdf-hooks:begin -->"
DOC_END = "<!-- sdf-hooks:end -->"

# A marker candidate: the kind word, then either "[ID]" or anything else (a bare marker is an error).
_CANDIDATE = re.compile(r"(?<!`)\b(ALGORITHM|DATA)-HOOK(?!`)(\[(?P<id>[A-Z][0-9]+)\])?")
_CHECKLIST_ROW = re.compile(r"^\|\s*(?P<id>[A-Z][0-9]+)\s*\|\s*(?P<title>[^|]+?)\s*\|", re.MULTILINE)


@dataclass(frozen=True)
class Hook:
    kind: str  # "ALGORITHM" | "DATA"
    id: str | None  # None for a bare marker, which is an error
    path: str  # relative to the package's parent, e.g. "sdf/analytics/demand.py"
    line: int
    symbol: str  # enclosing "Class.method" / "function", or "" at module level

    @property
    def location(self) -> str:
        return f"{self.path}::{self.symbol}" if self.symbol else self.path


def _symbols(tree: ast.AST) -> list[tuple[int, int, str]]:
    """(first line, last line, dotted name) of every function and class, outermost first."""
    spans: list[tuple[int, int, str]] = []

    def visit(node: ast.AST, prefix: str) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                name = f"{prefix}{child.name}"
                spans.append((child.lineno, child.end_lineno or child.lineno, name))
                visit(child, name + ".")
            else:
                visit(child, prefix)

    visit(tree, "")
    return spans


def scan(package: Path = PACKAGE) -> list[Hook]:
    """Every marker in the package's source files (tests excluded), in file and line order."""
    hooks: list[Hook] = []
    for path in sorted(package.rglob("*.py")):
        if path.name.endswith("_test.py") or path.name == "conftest.py":
            continue
        text = path.read_text(encoding="utf-8")
        spans = _symbols(ast.parse(text))
        rel = path.relative_to(package.parent).as_posix()
        for lineno, line in enumerate(text.splitlines(), start=1):
            for m in _CANDIDATE.finditer(line):
                enclosing = [name for start, end, name in spans if start <= lineno <= end]
                hooks.append(Hook(m.group(1), m.group("id"), rel, lineno, enclosing[-1] if enclosing else ""))
    return hooks


def checklist_ids(text: str) -> dict[str, str]:
    """Row ID → title of every table row in the checklist, outside the generated block."""
    if DOC_BEGIN in text and DOC_END in text:
        text = text[: text.index(DOC_BEGIN)] + text[text.index(DOC_END) + len(DOC_END) :]
    return {m.group("id"): m.group("title") for m in _CHECKLIST_ROW.finditer(text)}


def render_index(hooks: list[Hook], ids: dict[str, str]) -> str:
    """The generated section: one row per checklist ID with the locations that plug into it."""
    lines = [
        "_Generated by `uv run sdf hooks --update-doc docs/ALGORITHM_AND_DATA_CHECKLIST.md`; do not edit by hand._",
        "",
        "| # | Item | Algorithm hooks | Data hooks |",
        "|---|---|---|---|",
    ]
    for row_id, title in ids.items():
        cells = []
        for kind in ("ALGORITHM", "DATA"):
            locations = sorted({h.location for h in hooks if h.id == row_id and h.kind == kind})
            cells.append("<br>".join(f"`{loc}`" for loc in locations) or "—")
        lines.append(f"| {row_id} | {title} | {cells[0]} | {cells[1]} |")
    return "\n".join(lines) + "\n"


def problems(hooks: list[Hook], ids: dict[str, str]) -> list[str]:
    """Bare markers and markers naming an ID the checklist does not have."""
    out = []
    for h in hooks:
        if h.id is None:
            out.append(f"{h.path}:{h.line}: {h.kind}-HOOK without a checklist ID")
        elif h.id not in ids:
            out.append(f"{h.path}:{h.line}: {h.kind}-HOOK[{h.id}] names no checklist row")
    return out


def replace_doc_block(text: str, block: str) -> str:
    """Return ``text`` with the content between the ``sdf-hooks`` markers replaced by ``block``."""
    begin, end = text.find(DOC_BEGIN), text.find(DOC_END)
    if begin < 0 or end < begin:
        raise ValueError(f"document has no {DOC_BEGIN} … {DOC_END} block")
    return text[: begin + len(DOC_BEGIN)] + "\n" + block + text[end:]


def doc_block(text: str) -> str:
    """Return the current content between the ``sdf-hooks`` markers."""
    begin, end = text.find(DOC_BEGIN), text.find(DOC_END)
    if begin < 0 or end < begin:
        raise ValueError(f"document has no {DOC_BEGIN} … {DOC_END} block")
    return text[begin + len(DOC_BEGIN) + 1 : end]
